language: swift  
osx_image: xcode9.2
xcode_workspace: app/PRESTO-Wallet.xcworkspace
xcode_scheme: PRESTO-Wallet
before_install:
  - gem install xcpretty -N
script:
    - set -o pipefail
    - xcodebuild clean test -workspace app/PRESTO-Wallet.xcworkspace -scheme PRESTO-Wallet -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -c
    - swiftlint --path app/
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
